// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/graphdist_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_dist
List get_dist(DataFrame x, int node, int d, int max_n);
RcppExport SEXP _graphdist_get_dist(SEXP xSEXP, SEXP nodeSEXP, SEXP dSEXP, SEXP max_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type max_n(max_nSEXP);
    rcpp_result_gen = Rcpp::wrap(get_dist(x, node, d, max_n));
    return rcpp_result_gen;
END_RCPP
}
// get_distsparse
List get_distsparse(RcppSparse::Matrix& mat, LogicalVector& member, std::size_t node, int d);
RcppExport SEXP _graphdist_get_distsparse(SEXP matSEXP, SEXP memberSEXP, SEXP nodeSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RcppSparse::Matrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< LogicalVector& >::type member(memberSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(get_distsparse(mat, member, node, d));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_node_count_dist
List rcpp_node_count_dist(RcppSparse::Matrix& mat, LogicalVector& member, IntegerVector from, int d);
RcppExport SEXP _graphdist_rcpp_node_count_dist(SEXP matSEXP, SEXP memberSEXP, SEXP fromSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RcppSparse::Matrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< LogicalVector& >::type member(memberSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_node_count_dist(mat, member, from, d));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_graphdist_get_dist", (DL_FUNC) &_graphdist_get_dist, 4},
    {"_graphdist_get_distsparse", (DL_FUNC) &_graphdist_get_distsparse, 4},
    {"_graphdist_rcpp_node_count_dist", (DL_FUNC) &_graphdist_rcpp_node_count_dist, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_graphdist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
