# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_get_dist <- function(x, node, d, max_n) {
    .Call(`_graphdist_rcpp_get_dist`, x, node, d, max_n)
}

rcpp_get_dist_sparse <- function(mat, member, node, max_d) {
    .Call(`_graphdist_rcpp_get_dist_sparse`, mat, member, node, max_d)
}

rcpp_member_distance <- function(mat, member, from, max_d) {
    .Call(`_graphdist_rcpp_member_distance`, mat, member, from, max_d)
}

rcpp_get_member_distance3 <- function(E, member, from_nodes, max_d = 3L, nthreads = -1L) {
    .Call(`_graphdist_rcpp_get_member_distance3`, E, member, from_nodes, max_d, nthreads)
}

rcpp_get_dist_sparse2 <- function(mat, member, node, max_d) {
    .Call(`_graphdist_rcpp_get_dist_sparse2`, mat, member, node, max_d)
}

rcpp_member_distance2 <- function(mat, member, from, max_d, ncores = 1L) {
    .Call(`_graphdist_rcpp_member_distance2`, mat, member, from, max_d, ncores)
}

rcpp_to_spam_sorted <- function(from, to, N) {
    .Call(`_graphdist_rcpp_to_spam_sorted`, from, to, N)
}

rcpp_to_spam <- function(from, to, N) {
    .Call(`_graphdist_rcpp_to_spam`, from, to, N)
}

